# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm install
      - name: Test project with ESlint
        run: make lint
      - name: Test project with Jest
        run: npm run test
      - name: Set git config and add changes
        run: |
          git config --global user.email "${{secrets.REPO_EMAIL}}"
          git config --global user.name "${GITHUB_ACTOR}"
      - name: Deploy project on Github Pages
        run: npm run deploy
